"""Initial migration

Revision ID: a46be0ae733d
Revises: 3c5b6500e237
Create Date: 2026-02-27 18:32:12.827243

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a46be0ae733d'
down_revision = '3c5b6500e237'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
